import { Category, DeliveryConfig, District, Product } from "../types";

export const seedCategories: Category[] = [
  { id: "cat-vestidos", name: "Vestidos", slug: "vestidos" },
  { id: "cat-blusas", name: "Blusas", slug: "blusas" },
  { id: "cat-pantalones", name: "Pantalones", slug: "pantalones" },
  { id: "cat-faldas", name: "Faldas", slug: "faldas" },
  { id: "cat-polos", name: "Polos", slug: "polos" },
  { id: "cat-accesorios", name: "Accesorios", slug: "accesorios" },
];

const now = new Date().toISOString();

export const seedProducts: Product[] = [
  {
    id: "prod-001",
    code: "VE-001",
    name: "Vestido Floral Primavera",
    description:
      "Vestido midi con estampado floral, tela fresca y ligera, ideal para el verano limeño. Corte que favorece todas las siluetas.",
    categoryId: "cat-vestidos",
    color: "Rosado floral",
    price: 89.9,
    salePrice: 69.9,
    photos: ["/uploads/vestido-floral.svg"],
    variants: [
      { size: "S", quantity: 8 },
      { size: "M", quantity: 12 },
      { size: "L", quantity: 5 },
    ],
    active: true,
    createdAt: now,
  },
  {
    id: "prod-002",
    code: "VE-002",
    name: "Vestido Negro Elegante",
    description:
      "El clásico vestido negro que no puede faltar. Perfecto para una cena o una reunión importante.",
    categoryId: "cat-vestidos",
    color: "Negro",
    price: 119.9,
    salePrice: null,
    photos: ["/uploads/vestido-negro.svg"],
    variants: [
      { size: "S", quantity: 6 },
      { size: "M", quantity: 9 },
      { size: "L", quantity: 4 },
      { size: "XL", quantity: 3 },
    ],
    active: true,
    createdAt: now,
  },
  {
    id: "prod-003",
    code: "BL-001",
    name: "Blusa Satinada Champagne",
    description:
      "Blusa de satén con caída elegante y botones perlados. Combina con jeans o falda para un look versátil.",
    categoryId: "cat-blusas",
    color: "Champagne",
    price: 59.9,
    salePrice: 45.9,
    photos: ["/uploads/blusa-satinada.svg"],
    variants: [
      { size: "S", quantity: 10 },
      { size: "M", quantity: 14 },
      { size: "L", quantity: 7 },
    ],
    active: true,
    createdAt: now,
  },
  {
    id: "prod-004",
    code: "BL-002",
    name: "Blusa Blanca Manga Bombacha",
    description:
      "Blusa blanca de algodón con mangas bombachas y cuello cuadrado. Fresca, cómoda y muy femenina.",
    categoryId: "cat-blusas",
    color: "Blanco",
    price: 49.9,
    salePrice: null,
    photos: ["/uploads/blusa-blanca.svg"],
    variants: [
      { size: "S", quantity: 12 },
      { size: "M", quantity: 15 },
      { size: "L", quantity: 8 },
    ],
    active: true,
    createdAt: now,
  },
  {
    id: "prod-005",
    code: "PA-001",
    name: "Jean Mom Fit Tiro Alto",
    description:
      "Jean mom fit de tiro alto, denim suave con stretch. El básico favorito de todas.",
    categoryId: "cat-pantalones",
    color: "Azul medio",
    price: 99.9,
    salePrice: 79.9,
    photos: ["/uploads/jean-momfit.svg"],
    variants: [
      { size: "26", quantity: 6 },
      { size: "28", quantity: 10 },
      { size: "30", quantity: 8 },
      { size: "32", quantity: 4 },
    ],
    active: true,
    createdAt: now,
  },
  {
    id: "prod-006",
    code: "PA-002",
    name: "Pantalón Palazzo Lino",
    description:
      "Pantalón palazzo de lino fresco color arena. Elegante y cómodo para el día a día.",
    categoryId: "cat-pantalones",
    color: "Arena",
    price: 79.9,
    salePrice: null,
    photos: ["/uploads/pantalon-palazzo.svg"],
    variants: [
      { size: "S", quantity: 7 },
      { size: "M", quantity: 9 },
      { size: "L", quantity: 5 },
    ],
    active: true,
    createdAt: now,
  },
  {
    id: "prod-007",
    code: "FA-001",
    name: "Falda Plisada Midi",
    description:
      "Falda plisada midi color terracota con cintura elástica. Movimiento y estilo en una sola prenda.",
    categoryId: "cat-faldas",
    color: "Terracota",
    price: 65.9,
    salePrice: 52.9,
    photos: ["/uploads/falda-plisada.svg"],
    variants: [
      { size: "S", quantity: 9 },
      { size: "M", quantity: 11 },
      { size: "L", quantity: 6 },
    ],
    active: true,
    createdAt: now,
  },
  {
    id: "prod-008",
    code: "PO-001",
    name: "Polo Básico Algodón Pima",
    description:
      "Polo de algodón pima peruano, suave y duradero. Disponible en color lila pastel.",
    categoryId: "cat-polos",
    color: "Lila",
    price: 35.9,
    salePrice: null,
    photos: ["/uploads/polo-basico.svg"],
    variants: [
      { size: "S", quantity: 20 },
      { size: "M", quantity: 25 },
      { size: "L", quantity: 15 },
      { size: "XL", quantity: 10 },
    ],
    active: true,
    createdAt: now,
  },
  {
    id: "prod-009",
    code: "PO-002",
    name: "Polo Crop Rib",
    description:
      "Polo crop acanalado de manga corta. Juvenil y combinable con jeans de tiro alto.",
    categoryId: "cat-polos",
    color: "Verde oliva",
    price: 29.9,
    salePrice: 24.9,
    photos: ["/uploads/polo-crop.svg"],
    variants: [
      { size: "S", quantity: 14 },
      { size: "M", quantity: 16 },
      { size: "L", quantity: 9 },
    ],
    active: true,
    createdAt: now,
  },
  {
    id: "prod-010",
    code: "AC-001",
    name: "Cartera Tote Vegana",
    description:
      "Cartera tote de cuero vegano color camel. Amplia, resistente y con bolsillo interior.",
    categoryId: "cat-accesorios",
    color: "Camel",
    price: 75.9,
    salePrice: null,
    photos: ["/uploads/cartera-tote.svg"],
    variants: [{ size: "Única", quantity: 12 }],
    active: true,
    createdAt: now,
  },
];

// Distritos de Lima con coordenadas aproximadas de su centro
export const seedDistricts: District[] = [
  { id: "dist-miraflores", name: "Miraflores", lat: -12.1211, lng: -77.0297, surcharge: 0 },
  { id: "dist-san-isidro", name: "San Isidro", lat: -12.0976, lng: -77.0365, surcharge: 0 },
  { id: "dist-barranco", name: "Barranco", lat: -12.14, lng: -77.021, surcharge: 0 },
  { id: "dist-surco", name: "Santiago de Surco", lat: -12.1355, lng: -76.993, surcharge: 0 },
  { id: "dist-la-molina", name: "La Molina", lat: -12.079, lng: -76.939, surcharge: 0 },
  { id: "dist-san-borja", name: "San Borja", lat: -12.1027, lng: -76.9989, surcharge: 0 },
  { id: "dist-jesus-maria", name: "Jesús María", lat: -12.0705, lng: -77.048, surcharge: 0 },
  { id: "dist-lince", name: "Lince", lat: -12.085, lng: -77.036, surcharge: 0 },
  { id: "dist-magdalena", name: "Magdalena del Mar", lat: -12.091, lng: -77.071, surcharge: 0 },
  { id: "dist-pueblo-libre", name: "Pueblo Libre", lat: -12.074, lng: -77.063, surcharge: 0 },
  { id: "dist-san-miguel", name: "San Miguel", lat: -12.077, lng: -77.091, surcharge: 0 },
  { id: "dist-cercado", name: "Cercado de Lima", lat: -12.0464, lng: -77.0428, surcharge: 0 },
  { id: "dist-brena", name: "Breña", lat: -12.057, lng: -77.05, surcharge: 0 },
  { id: "dist-la-victoria", name: "La Victoria", lat: -12.065, lng: -77.015, surcharge: 0 },
  { id: "dist-surquillo", name: "Surquillo", lat: -12.111, lng: -77.017, surcharge: 0 },
  { id: "dist-chorrillos", name: "Chorrillos", lat: -12.168, lng: -77.024, surcharge: 0 },
  { id: "dist-sjm", name: "San Juan de Miraflores", lat: -12.155, lng: -76.97, surcharge: 2 },
  { id: "dist-ves", name: "Villa El Salvador", lat: -12.213, lng: -76.939, surcharge: 3 },
  { id: "dist-sjl", name: "San Juan de Lurigancho", lat: -12.003, lng: -77.008, surcharge: 3 },
  { id: "dist-los-olivos", name: "Los Olivos", lat: -11.991, lng: -77.071, surcharge: 3 },
  { id: "dist-smp", name: "San Martín de Porres", lat: -12.009, lng: -77.085, surcharge: 3 },
  { id: "dist-comas", name: "Comas", lat: -11.943, lng: -77.062, surcharge: 4 },
  { id: "dist-ate", name: "Ate", lat: -12.026, lng: -76.921, surcharge: 3 },
  { id: "dist-santa-anita", name: "Santa Anita", lat: -12.043, lng: -76.971, surcharge: 2 },
  { id: "dist-callao", name: "Callao", lat: -12.056, lng: -77.118, surcharge: 3 },
  { id: "dist-rimac", name: "Rímac", lat: -12.029, lng: -77.028, surcharge: 2 },
];

// La tienda está en Miraflores; tarifa = max(minFee, baseFee + perKmFee * km + recargo distrito)
export const seedDeliveryConfig: DeliveryConfig = {
  originLat: -12.1211,
  originLng: -77.0297,
  baseFee: 8,
  perKmFee: 1.2,
  minFee: 8,
  freeThreshold: 200,
};
